stages:
  - mirror
  - test
  - deploy
  - docstats

mirror_repo:
  stage: mirror
  only:
    - master
    - develop
  script:
    - git checkout master
    - git push -u git@github.com:namboy94/puffotter.git HEAD:master --force
    - git checkout develop
    - git push -u git@github.com:namboy94/puffotter.git HEAD:develop --force

run_unit_tests:
  stage: test
  script:
    - python3 setup.py test

source_dist:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py register sdist upload

binary_3_dist:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py bdist_wheel upload

binary_2_dist:
  stage: deploy
  only:
    - master
  script:
    - 3to2 . --write
    - python2 setup.py bdist_wheel upload

generate_documentation:
  stage: docstats
  only:
    - master
    - develop
  script:
    - cd doc
    - make buildsource
    - make html
    - make latexpdf
  artifacts:
    paths:
      - doc/build/html
      - doc/build/latex/puffotter.pdf

generate_statistics:
  stage: docstats
  only:
    - master
    - develop
  script:
    - gitstats . git_stats
  artifacts:
    paths:
      - git_stats

upload_docstats:
  stage: docstats:
  only:
    - master
    - develop
  script:
    - git clone git@gitlab.namibsun.net:/namboy94/puffotter.wiki
    - cd puffotter.wiki
    - mv ../doc/build/html .
    - mv ../git_stats .
    - mv ../doc/build/latex/puffotter.pdf .

