stages:
  - mirror
  - test
  - deploy

clone_repo:
  stage: mirror
  only:
    - master
    - develop
  script:
    - git push -u git@github.com:namboy94/puffotter.git --all

run_unit_tests:
  stage: test
  script:
    - python3 setup.py test

upload_to_pypi:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py register sdist upload