stages:
  - setup
  - mirror
  - test
  - deploy

environment_check:
  stage: setup
  script:
    - pip3 install wheel --user

mirror_repo:
  stage: mirror
  only:
    - master
    - develop
  script:
    - git checkout master
    - git push -u git@github.com:namboy94/puffotter.git HEAD:master --force
    - git checkout develop
    - git push -u git@github.com:namboy94/puffotter.git HEAD:develop --force

run_unit_tests:
  stage: test
  script:
    - python3 setup.py test

source_dist:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py register sdist upload

binary_3_dist:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py bdist_wheel upload

binary_2_dist:
  stage: deploy
  only:
    - master
  script:
    - 3to2 . --write
    - python2 setup.py bdist_wheel upload
